// Generated by gencpp from file vehicle_msgs/ThrustCommand.msg
// DO NOT EDIT!


#ifndef VEHICLE_MSGS_MESSAGE_THRUSTCOMMAND_H
#define VEHICLE_MSGS_MESSAGE_THRUSTCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vehicle_msgs
{
template <class ContainerAllocator>
struct ThrustCommand_
{
  typedef ThrustCommand_<ContainerAllocator> Type;

  ThrustCommand_()
    : rpm(0.0)
    , parsentage(0.0)  {
    }
  ThrustCommand_(const ContainerAllocator& _alloc)
    : rpm(0.0)
    , parsentage(0.0)  {
  (void)_alloc;
    }



   typedef double _rpm_type;
  _rpm_type rpm;

   typedef double _parsentage_type;
  _parsentage_type parsentage;





  typedef boost::shared_ptr< ::vehicle_msgs::ThrustCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_msgs::ThrustCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ThrustCommand_

typedef ::vehicle_msgs::ThrustCommand_<std::allocator<void> > ThrustCommand;

typedef boost::shared_ptr< ::vehicle_msgs::ThrustCommand > ThrustCommandPtr;
typedef boost::shared_ptr< ::vehicle_msgs::ThrustCommand const> ThrustCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_msgs::ThrustCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_msgs::ThrustCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vehicle_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'vehicle_msgs': ['/home/ubuntu/catkin_ws/src/vehicle_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::ThrustCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::ThrustCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::ThrustCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::ThrustCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::ThrustCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::ThrustCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_msgs::ThrustCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ddf5f4cc143c036adb2fabd0af5bfc0";
  }

  static const char* value(const ::vehicle_msgs::ThrustCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ddf5f4cc143c036ULL;
  static const uint64_t static_value2 = 0xadb2fabd0af5bfc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_msgs::ThrustCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_msgs/ThrustCommand";
  }

  static const char* value(const ::vehicle_msgs::ThrustCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_msgs::ThrustCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 rpm\n"
"float64 parsentage\n"
;
  }

  static const char* value(const ::vehicle_msgs::ThrustCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_msgs::ThrustCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rpm);
      stream.next(m.parsentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThrustCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_msgs::ThrustCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_msgs::ThrustCommand_<ContainerAllocator>& v)
  {
    s << indent << "rpm: ";
    Printer<double>::stream(s, indent + "  ", v.rpm);
    s << indent << "parsentage: ";
    Printer<double>::stream(s, indent + "  ", v.parsentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MSGS_MESSAGE_THRUSTCOMMAND_H
