// Generated by gencpp from file vehicle_msgs/ThrustersState.msg
// DO NOT EDIT!


#ifndef VEHICLE_MSGS_MESSAGE_THRUSTERSSTATE_H
#define VEHICLE_MSGS_MESSAGE_THRUSTERSSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vehicle_msgs/ThrustState.h>
#include <vehicle_msgs/ThrustState.h>
#include <vehicle_msgs/ThrustState.h>
#include <vehicle_msgs/ThrustState.h>
#include <vehicle_msgs/ThrustState.h>
#include <vehicle_msgs/ThrustState.h>

namespace vehicle_msgs
{
template <class ContainerAllocator>
struct ThrustersState_
{
  typedef ThrustersState_<ContainerAllocator> Type;

  ThrustersState_()
    : Thruster1()
    , Thruster2()
    , Thruster3()
    , Thruster4()
    , Thruster5()
    , Thruster6()  {
    }
  ThrustersState_(const ContainerAllocator& _alloc)
    : Thruster1(_alloc)
    , Thruster2(_alloc)
    , Thruster3(_alloc)
    , Thruster4(_alloc)
    , Thruster5(_alloc)
    , Thruster6(_alloc)  {
  (void)_alloc;
    }



   typedef  ::vehicle_msgs::ThrustState_<ContainerAllocator>  _Thruster1_type;
  _Thruster1_type Thruster1;

   typedef  ::vehicle_msgs::ThrustState_<ContainerAllocator>  _Thruster2_type;
  _Thruster2_type Thruster2;

   typedef  ::vehicle_msgs::ThrustState_<ContainerAllocator>  _Thruster3_type;
  _Thruster3_type Thruster3;

   typedef  ::vehicle_msgs::ThrustState_<ContainerAllocator>  _Thruster4_type;
  _Thruster4_type Thruster4;

   typedef  ::vehicle_msgs::ThrustState_<ContainerAllocator>  _Thruster5_type;
  _Thruster5_type Thruster5;

   typedef  ::vehicle_msgs::ThrustState_<ContainerAllocator>  _Thruster6_type;
  _Thruster6_type Thruster6;





  typedef boost::shared_ptr< ::vehicle_msgs::ThrustersState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_msgs::ThrustersState_<ContainerAllocator> const> ConstPtr;

}; // struct ThrustersState_

typedef ::vehicle_msgs::ThrustersState_<std::allocator<void> > ThrustersState;

typedef boost::shared_ptr< ::vehicle_msgs::ThrustersState > ThrustersStatePtr;
typedef boost::shared_ptr< ::vehicle_msgs::ThrustersState const> ThrustersStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_msgs::ThrustersState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_msgs::ThrustersState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vehicle_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'vehicle_msgs': ['/home/ubuntu/catkin_ws/src/vehicle_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::ThrustersState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::ThrustersState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::ThrustersState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::ThrustersState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::ThrustersState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::ThrustersState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_msgs::ThrustersState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fe2acc0070e119df72824cb8968d31b";
  }

  static const char* value(const ::vehicle_msgs::ThrustersState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fe2acc0070e119dULL;
  static const uint64_t static_value2 = 0xf72824cb8968d31bULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_msgs::ThrustersState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_msgs/ThrustersState";
  }

  static const char* value(const ::vehicle_msgs::ThrustersState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_msgs::ThrustersState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ThrustState Thruster1\n"
"ThrustState Thruster2\n"
"ThrustState Thruster3\n"
"ThrustState Thruster4\n"
"ThrustState Thruster5\n"
"ThrustState Thruster6\n"
"\n"
"================================================================================\n"
"MSG: vehicle_msgs/ThrustState\n"
"float64 rpm\n"
"float64 force\n"
"float64 valtage\n"
"float64 wattage\n"
;
  }

  static const char* value(const ::vehicle_msgs::ThrustersState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_msgs::ThrustersState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Thruster1);
      stream.next(m.Thruster2);
      stream.next(m.Thruster3);
      stream.next(m.Thruster4);
      stream.next(m.Thruster5);
      stream.next(m.Thruster6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThrustersState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_msgs::ThrustersState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_msgs::ThrustersState_<ContainerAllocator>& v)
  {
    s << indent << "Thruster1: ";
    s << std::endl;
    Printer< ::vehicle_msgs::ThrustState_<ContainerAllocator> >::stream(s, indent + "  ", v.Thruster1);
    s << indent << "Thruster2: ";
    s << std::endl;
    Printer< ::vehicle_msgs::ThrustState_<ContainerAllocator> >::stream(s, indent + "  ", v.Thruster2);
    s << indent << "Thruster3: ";
    s << std::endl;
    Printer< ::vehicle_msgs::ThrustState_<ContainerAllocator> >::stream(s, indent + "  ", v.Thruster3);
    s << indent << "Thruster4: ";
    s << std::endl;
    Printer< ::vehicle_msgs::ThrustState_<ContainerAllocator> >::stream(s, indent + "  ", v.Thruster4);
    s << indent << "Thruster5: ";
    s << std::endl;
    Printer< ::vehicle_msgs::ThrustState_<ContainerAllocator> >::stream(s, indent + "  ", v.Thruster5);
    s << indent << "Thruster6: ";
    s << std::endl;
    Printer< ::vehicle_msgs::ThrustState_<ContainerAllocator> >::stream(s, indent + "  ", v.Thruster6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MSGS_MESSAGE_THRUSTERSSTATE_H
