# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vehicle_msgs/ThrustersCommand.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import vehicle_msgs.msg

class ThrustersCommand(genpy.Message):
  _md5sum = "39aeea5206baf8dd8128d11e0a1a393a"
  _type = "vehicle_msgs/ThrustersCommand"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """ThrustCommand Thruster1
ThrustCommand Thruster2
ThrustCommand Thruster3
ThrustCommand Thruster4
ThrustCommand Thruster5
ThrustCommand Thruster6
string        mode

================================================================================
MSG: vehicle_msgs/ThrustCommand
float64 rpm
float64 parsentage
"""
  __slots__ = ['Thruster1','Thruster2','Thruster3','Thruster4','Thruster5','Thruster6','mode']
  _slot_types = ['vehicle_msgs/ThrustCommand','vehicle_msgs/ThrustCommand','vehicle_msgs/ThrustCommand','vehicle_msgs/ThrustCommand','vehicle_msgs/ThrustCommand','vehicle_msgs/ThrustCommand','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Thruster1,Thruster2,Thruster3,Thruster4,Thruster5,Thruster6,mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ThrustersCommand, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Thruster1 is None:
        self.Thruster1 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster2 is None:
        self.Thruster2 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster3 is None:
        self.Thruster3 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster4 is None:
        self.Thruster4 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster5 is None:
        self.Thruster5 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster6 is None:
        self.Thruster6 = vehicle_msgs.msg.ThrustCommand()
      if self.mode is None:
        self.mode = ''
    else:
      self.Thruster1 = vehicle_msgs.msg.ThrustCommand()
      self.Thruster2 = vehicle_msgs.msg.ThrustCommand()
      self.Thruster3 = vehicle_msgs.msg.ThrustCommand()
      self.Thruster4 = vehicle_msgs.msg.ThrustCommand()
      self.Thruster5 = vehicle_msgs.msg.ThrustCommand()
      self.Thruster6 = vehicle_msgs.msg.ThrustCommand()
      self.mode = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.Thruster1.rpm, _x.Thruster1.parsentage, _x.Thruster2.rpm, _x.Thruster2.parsentage, _x.Thruster3.rpm, _x.Thruster3.parsentage, _x.Thruster4.rpm, _x.Thruster4.parsentage, _x.Thruster5.rpm, _x.Thruster5.parsentage, _x.Thruster6.rpm, _x.Thruster6.parsentage))
      _x = self.mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.Thruster1 is None:
        self.Thruster1 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster2 is None:
        self.Thruster2 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster3 is None:
        self.Thruster3 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster4 is None:
        self.Thruster4 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster5 is None:
        self.Thruster5 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster6 is None:
        self.Thruster6 = vehicle_msgs.msg.ThrustCommand()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.Thruster1.rpm, _x.Thruster1.parsentage, _x.Thruster2.rpm, _x.Thruster2.parsentage, _x.Thruster3.rpm, _x.Thruster3.parsentage, _x.Thruster4.rpm, _x.Thruster4.parsentage, _x.Thruster5.rpm, _x.Thruster5.parsentage, _x.Thruster6.rpm, _x.Thruster6.parsentage,) = _get_struct_12d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mode = str[start:end].decode('utf-8')
      else:
        self.mode = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.Thruster1.rpm, _x.Thruster1.parsentage, _x.Thruster2.rpm, _x.Thruster2.parsentage, _x.Thruster3.rpm, _x.Thruster3.parsentage, _x.Thruster4.rpm, _x.Thruster4.parsentage, _x.Thruster5.rpm, _x.Thruster5.parsentage, _x.Thruster6.rpm, _x.Thruster6.parsentage))
      _x = self.mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.Thruster1 is None:
        self.Thruster1 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster2 is None:
        self.Thruster2 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster3 is None:
        self.Thruster3 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster4 is None:
        self.Thruster4 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster5 is None:
        self.Thruster5 = vehicle_msgs.msg.ThrustCommand()
      if self.Thruster6 is None:
        self.Thruster6 = vehicle_msgs.msg.ThrustCommand()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.Thruster1.rpm, _x.Thruster1.parsentage, _x.Thruster2.rpm, _x.Thruster2.parsentage, _x.Thruster3.rpm, _x.Thruster3.parsentage, _x.Thruster4.rpm, _x.Thruster4.parsentage, _x.Thruster5.rpm, _x.Thruster5.parsentage, _x.Thruster6.rpm, _x.Thruster6.parsentage,) = _get_struct_12d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mode = str[start:end].decode('utf-8')
      else:
        self.mode = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12d = None
def _get_struct_12d():
    global _struct_12d
    if _struct_12d is None:
        _struct_12d = struct.Struct("<12d")
    return _struct_12d
