// Generated by gencpp from file pt_msg/PanTiltAngles.msg
// DO NOT EDIT!


#ifndef PT_MSG_MESSAGE_PANTILTANGLES_H
#define PT_MSG_MESSAGE_PANTILTANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pt_msg
{
template <class ContainerAllocator>
struct PanTiltAngles_
{
  typedef PanTiltAngles_<ContainerAllocator> Type;

  PanTiltAngles_()
    : pan(0.0)
    , tilt(0.0)  {
    }
  PanTiltAngles_(const ContainerAllocator& _alloc)
    : pan(0.0)
    , tilt(0.0)  {
  (void)_alloc;
    }



   typedef double _pan_type;
  _pan_type pan;

   typedef double _tilt_type;
  _tilt_type tilt;





  typedef boost::shared_ptr< ::pt_msg::PanTiltAngles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pt_msg::PanTiltAngles_<ContainerAllocator> const> ConstPtr;

}; // struct PanTiltAngles_

typedef ::pt_msg::PanTiltAngles_<std::allocator<void> > PanTiltAngles;

typedef boost::shared_ptr< ::pt_msg::PanTiltAngles > PanTiltAnglesPtr;
typedef boost::shared_ptr< ::pt_msg::PanTiltAngles const> PanTiltAnglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pt_msg::PanTiltAngles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pt_msg::PanTiltAngles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pt_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'pt_msg': ['/home/ubuntu/catkin_ws/src/pt_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pt_msg::PanTiltAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pt_msg::PanTiltAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pt_msg::PanTiltAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pt_msg::PanTiltAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pt_msg::PanTiltAngles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pt_msg::PanTiltAngles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pt_msg::PanTiltAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da61f3d6b381bd4af7a066f22fdfa441";
  }

  static const char* value(const ::pt_msg::PanTiltAngles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda61f3d6b381bd4aULL;
  static const uint64_t static_value2 = 0xf7a066f22fdfa441ULL;
};

template<class ContainerAllocator>
struct DataType< ::pt_msg::PanTiltAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pt_msg/PanTiltAngles";
  }

  static const char* value(const ::pt_msg::PanTiltAngles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pt_msg::PanTiltAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pan\n"
"float64 tilt\n"
;
  }

  static const char* value(const ::pt_msg::PanTiltAngles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pt_msg::PanTiltAngles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pan);
      stream.next(m.tilt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PanTiltAngles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pt_msg::PanTiltAngles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pt_msg::PanTiltAngles_<ContainerAllocator>& v)
  {
    s << indent << "pan: ";
    Printer<double>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<double>::stream(s, indent + "  ", v.tilt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PT_MSG_MESSAGE_PANTILTANGLES_H
